buildscript {
    repositories {
        mavenCentral()
    }
    dependencies {
        classpath 'commons-io:commons-io:2.18.0'
    }
}

import org.apache.commons.io.FileUtils
import org.apache.commons.io.filefilter.FalseFileFilter
import org.apache.commons.io.filefilter.PrefixFileFilter

tasks.register('genGuideResources') {
    group = 'build'
    description = 'Create a resource pack from translating the guides'
    doLast {
        File buildDir = project.layout.buildDirectory.get().asFile as File
        File rootDir = project.layout.projectDirectory.asFile as File
        var guidesDstDir = new File(buildDir, 'guides')
        var guideSrcDir = new File(rootDir, 'guide')
        var langDirs = FileUtils.listFilesAndDirs(guideSrcDir, FalseFileFilter.FALSE, new PrefixFileFilter('_')).dropRight(1)

        for (var langDir : langDirs) {
            var langCode = langDir.getName().substring(1)
            var packName = resourcePackName(langCode)
            var packDir = copyTemplate(packName, guidesDstDir)
            copyGuide(packDir, langDir)
            zipAndDelete(packDir)
        }

        return guidesDstDir
    }
}

/**
 * language to resource pack file name
 */
def resourcePackName(String language) {
    return "${language} ${rootProject.name} ${project.version}"
}

/**
 * move template dir to build
 */
static def copyTemplate(String packName, File to) {
    var src = new File('resources_template')
    var dst = new File(to, packName)
    FileUtils.copyDirectory(src, dst)
    return dst
}

/**
 * copy specific language guide
 */
static def copyGuide(File packDir, File langDir) {
    var guideRoot = new File(packDir.absolutePath, 'assets/pccard/ae2guide')
    print(guideRoot)
    FileUtils.copyDirectory(langDir, guideRoot)
}

/**
 * create zip file and delete directory
 */
def zipAndDelete(File targetDir) {
    var name = targetDir.name
    var parent = targetDir.parentFile
    var zipFile = new File(parent, "${name}.zip")
    ant.zip(destfile: zipFile) {
        fileset(dir: targetDir)
    }

    println "ZIP created at: ${targetDir}"

    targetDir.deleteDir()
}
